apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
  namespace: django-project-name
  labels:
    app: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: pogossian/django-k8s:1.0.8
        command: ['celery', '-A', 'project_name', 'worker', '-l', 'info']
        imagePullPolicy: "Always"
        env:
          - name: django_db_user
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: user
          - name: django_db_pass
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: django_db_engine
            value: django.db.backends.mysql
          - name: django_db_name
            value: db
          - name: django_db_host
            value: db
          - name: django_db_port
            value: "3306"
          - name: django_redis_host
            value: redis-project-name-service
          - name: django_redis_port
            value: "6379"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: django-project-name
  labels:
    app: celery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: pogossian/django-k8s:1.0.8
        command: ['celery', '-A', 'project_name', 'beat', '-l', 'info']
        imagePullPolicy: "Always"
        env:
          - name: django_db_user
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: user
          - name: django_db_pass
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: django_db_engine
            value: django.db.backends.mysql
          - name: django_db_name
            value: db
          - name: django_db_host
            value: db
          - name: django_db_port
            value: "3306"
          - name: django_redis_host
            value: redis-project-name-service
          - name: django_redis_port
            value: "6379"

