apiVersion: v1
kind: Namespace
metadata:
  name: django-project-name

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: project-name-pv
  namespace: django-project-name
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.62.62.200
    path: /storage-1/kub-pv/project-name


---


apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: django-project-name
type: Opaque
data:
  user: cm9vdA==
  password: MTIzNA==