apiVersion: v1
kind: Namespace
metadata:
  name: django-{{ .Values.name }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.name }}-pv
  namespace: django-{{ .Values.name }}
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.62.62.200
    path: /storage-1/kub-pv/{{ .Values.name }}


---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-{{ .Values.name }}-pv-claim
  namespace: django-{{ .Values.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi


---

apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: django-{{ .Values.name }}
type: Opaque
data:
  user: {{ .Values.db.user }}
  password: {{ .Values.db.password }}