apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-{{ .Values.name }}
  namespace: django-{{ .Values.name }}
  labels:
    app: redis-{{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-{{ .Values.name }}
  template:
    metadata:
      labels:
        app: redis-{{ .Values.name }}
    spec:
      containers:
      - name: redis-{{ .Values.name }}
        image: redis
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-{{ .Values.name }}-service
  namespace: django-{{ .Values.name }}
  labels:
    app: redis-{{ .Values.name }}
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis-{{ .Values.name }}
  type: ClusterIP