apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.host }}
  namespace: django-{{ .Values.name }}
  labels:
    app: mysql-{{ .Values.name }}
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mysql-{{ .Values.name }}
  type: ClusterIP

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-{{ .Values.name }}
  namespace: django-{{ .Values.name }}
  labels:
    app: mysql-{{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-{{ .Values.name }}
  serviceName: {{ .Values.db.host }}
  template:
    metadata:
      labels:
        app: mysql-{{ .Values.name }}
    spec:
      containers:
      - name: mysql-{{ .Values.name }}
        image: mysql:5.7
        imagePullPolicy: "Always"
        args:
          - --character-set-server=utf8
          - --collation-server=utf8_general_ci
        env:
        - name: "MYSQL_DATABASE"
          value: "{{ .Values.db.name }}"
        - name: "MYSQL_ROOT_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        ports:
        - containerPort: 3306
        resources:
          limits:
            memory: 512Mi
        volumeMounts:
        - name: mysql-{{ .Values.name }}-persistent-storage
          mountPath: /var/lib/mysql
          subPath: mysql-server
      volumes:
      - name: mysql-{{ .Values.name }}-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-{{ .Values.name }}-pv-claim
